###
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY2MDYwNzAxNH0.FhXOQ8LKb_nprZF-tJ-NuJulDxG0ODeKW-qBiY8th-A

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Kyle"
}